
// set up the nodeDataArray, describing each person/position
// key, predecessor, name, alternativeName, rating, rulerOf, 
// ** ATTRIBUTES TO ADD : ReignLength, Chapters 
// ** ADD new node template when captured? Circle?
var nodeDataArray = [
    { key: "Saul_1", name: "Saul", rating: "mixed", rulerOf: "Israel and Judah" },
    { key: "David_1", predecessor: "Saul_1", name: "David", rating: "good", rulerOf: "Israel and Judah" },
    { key: "Solomon_1", predecessor: "David_1", name: "Solomon", rating: "good", rulerOf: "Israel and Judah" },
    { key: "Rehoboam_1", predecessor: "Solomon_1", name: "Rehoboam", rating: "bad", rulerOf: "Judah" },
    { key: "Abijam_1", predecessor: "Rehoboam_1", name: "Abijam", alternativeName: "Abijah", rating: "bad", rulerOf: "Judah" },
    { key: "Asa_1", predecessor: "Abijam_1", name: "Asa", rating: "good", rulerOf: "Judah" },
    { key: "Jehoshaphat_1", predecessor: "Asa_1", name: "Jehoshaphat", rating: "good", rulerOf: "Judah" },
    { key: "Johoram_1", predecessor: "Jehoshaphat_1", name: "Johoram", rating: "bad", rulerOf: "Judah" },
    { key: "Ahaziah_1", predecessor: "Johoram_1", name: "Ahaziah", rating: "bad", rulerOf: "Judah" },
    { key: "Athaliah_1", predecessor: "Ahaziah_1", name: "Athaliah", rating: "bad", rulerOf: "Judah" },
    { key: "Jehoash_1", predecessor: "Athaliah_1", name: "Jehoash", rating: "good", rulerOf: "Judah" },
    { key: "Amaziah_1", predecessor: "Jehoash_1", name: "Amaziah", rating: "good", rulerOf: "Judah" },
    { key: "Azariah_1", predecessor: "Amaziah_1", name: "Azaraih", alternativeName: "Uzziah", rating: "good", rulerOf: "Judah" },
    { key: "Jotham_1", predecessor: "Azariah_1", name: "Jotham", rating: "good", rulerOf: "Judah" },
    { key: "Ahaz_1", predecessor: "Jotham_1", name: "Ahaz", rating: "bad", rulerOf: "Judah" },
    { key: "Hezekiah_1", predecessor: "Ahaz_1", name: "Hezekiah", rating: "good", rulerOf: "Judah" },
    { key: "Manasseh_1", predecessor: "Hezekiah_1", name: "Manasseh", rating: "mixed", rulerOf: "Judah" },
    { key: "Amon_1", predecessor: "Manasseh_1", name: "Amon", rating: "bad", rulerOf: "Judah" },
    { key: "Josiah_1", predecessor: "Amon_1", name: "Josiah", rating: "good", rulerOf: "Judah" },
    { key: "Jehohaz_1", predecessor: "Josiah_1", name: "Jehohaz", rating: "bad", rulerOf: "Judah" },
    { key: "Jehoiakim_1", predecessor: "Jehohaz_1", name: "Jehoiakim", rating: "bad", rulerOf: "Judah" },
    { key: "Jehoiachin_1", predecessor: "Jehoiakim_1", name: "Jehoiachin", rating: "bad", rulerOf: "Judah" },
    { key: "Zedekiah_1", predecessor: "Jehoiachin_1", name: "Zedekiah", rating: "bad", rulerOf: "Judah" },
    { key: "Babylon Captivity", predecessor: "Zedekiah_1", name: "Babylon", captivity: "586 - 539BC", },

    // Israel
    { key: "Jeroboam_1", predecessor: "Solomon_1", name: "Jeroboam", rating: "bad", rulerOf: "Israel" },
    { key: "Nadab_1", predecessor: "Jeroboam_1", name: "Nadab", rating: "bad", rulerOf: "Israel" },
    { key: "Baasha_1", predecessor: "Nadab_1", name: "Baasha", rating: "bad", rulerOf: "Israel" },
    { key: "Elah_1", predecessor: "Baasha_1", name: "Elah", rating: "bad", rulerOf: "Israel" },
    { key: "Zimri_1", predecessor: "Elah_1", name: "Zimri", rating: "bad", rulerOf: "Israel" },
    { key: "Omri_1", predecessor: "Zimri_1", name: "Omri", rating: "bad", rulerOf: "Israel" },
    { key: "Ahab_1", predecessor: "Omri_1", name: "Ahab", rating: "bad", rulerOf: "Israel" },
    { key: "Ahaziah_2", predecessor: "Ahab_1", name: "Ahaziah", rating: "bad", rulerOf: "Israel" },
    { key: "Joram_1", predecessor: "Ahaziah_2", name: "Joram", rating: "bad", rulerOf: "Israel" },
    { key: "Jehu_1", predecessor: "Joram_1", name: "Jehu", rating: "good", rulerOf: "Israel" },
    { key: "Jehoahaz_2", predecessor: "Jehu_1", name: "Jehoahaz", rating: "bad", rulerOf: "Israel" },
    { key: "Jehoash_2", predecessor: "Jehoahaz_2", name: "Jehoash", rating: "bad", rulerOf: "Israel" },
    { key: "Jeroboam_2", predecessor: "Jehoash_2", name: "Jeroboam", rating: "bad", rulerOf: "Israel" },
    { key: "Zechariah_1", predecessor: "Jeroboam_2", name: "Zechariah", rating: "bad", rulerOf: "Israel" },
    { key: "Shallum_1", predecessor: "Zechariah_1", name: "Shallum", rating: "bad", rulerOf: "Israel" },
    { key: "Menahem_1", predecessor: "Shallum_1", name: "Menahem", rating: "bad", rulerOf: "Israel" },
    { key: "Pekahiah_1", predecessor: "Menahem_1", name: "Pekahiah", rating: "bad", rulerOf: "Israel" },
    { key: "Pekah_1", predecessor: "Pekahiah_1", name: "Pekah", rating: "bad", rulerOf: "Israel" },
    { key: "Hoshea_1", predecessor: "Pekah_1", name: "Hoshea", rating: "bad", rulerOf: "Israel" },
    { key: "Assyrian Captivity", predecessor: "Hoshea_1", name: "Assyria", captivity: "740 - 620BC", },

];